var namespaces_dup =
[
    [ "Analytics", "namespace_analytics.html", "namespace_analytics" ],
    [ "AssetPack", "namespace_asset_pack.html", "namespace_asset_pack" ],
    [ "Audio", "namespace_audio.html", "namespace_audio" ],
    [ "AutoTrestle", "namespace_auto_trestle.html", "namespace_auto_trestle" ],
    [ "Avatar", "namespace_avatar.html", "namespace_avatar" ],
    [ "BezierCurveMesh", "namespace_bezier_curve_mesh.html", "namespace_bezier_curve_mesh" ],
    [ "Cameras", "namespace_cameras.html", "namespace_cameras" ],
    [ "Character", "namespace_character.html", "namespace_character" ],
    [ "CSML", "namespace_c_s_m_l.html", "namespace_c_s_m_l" ],
    [ "Effects", "namespace_effects.html", "namespace_effects" ],
    [ "Enviro", "namespace_enviro.html", "namespace_enviro" ],
    [ "GalaSoft", "namespace_gala_soft.html", "namespace_gala_soft" ],
    [ "Game", "namespace_game.html", "namespace_game" ],
    [ "Helpers", "namespace_helpers.html", "namespace_helpers" ],
    [ "InfinityCode", "namespace_infinity_code.html", "namespace_infinity_code" ],
    [ "Logging", "namespace_logging.html", "namespace_logging" ],
    [ "Model", "namespace_model.html", "namespace_model" ],
    [ "Network", "namespace_network.html", "namespace_network" ],
    [ "RollingStock", "namespace_rolling_stock.html", "namespace_rolling_stock" ],
    [ "TelegraphPoles", "namespace_telegraph_poles.html", "namespace_telegraph_poles" ],
    [ "TerrainStitch", "namespace_terrain_stitch.html", "namespace_terrain_stitch" ],
    [ "Track", "namespace_track.html", "namespace_track" ],
    [ "TrainPhysics", "namespace_train_physics.html", "namespace_train_physics" ],
    [ "UI", "namespace_u_i.html", "namespace_u_i" ],
    [ "UnityStandardAssets", "namespace_unity_standard_assets.html", "namespace_unity_standard_assets" ],
    [ "VisualDesignCafe", "namespace_visual_design_cafe.html", "namespace_visual_design_cafe" ],
    [ "WorldStreamer2", "namespace_world_streamer2.html", "namespace_world_streamer2" ]
];